services:
  - type: web
    name: user-portal
    env: docker
    branch: main
    buildCommand: docker build -t user-portal .
    startCommand: docker run -p 8080:8080 user-portal
    envVars:
      - key: MYSQLHOST
        value: your-mysql-host
      - key: MYSQLUSER
        value: your-mysql-user
      - key: MYSQLPASSWORD
        value: your-mysql-password
      - key: MYSQLDATABASE
        value: your-database-name
